### ISSUE TITLE
Порты для локального режима

### ISSUE THREAD

**Issue by Andrywww** [AlexxIT/YandexStation#107]
Добрый день!

В сети две станции мини, HA стоит в Docker на Synology, нет возможности поменять тип сети, чтобы HA стал в той же сети что и станции.

Пытаюсь настроить локальный режим, прописал в конфиге параметры колонок, все равно не работает. 
```
yandex_station:
  device:
  ff98f039ffa6c58ebe089976:
  host: 192.168.10.168
  name: Яндекс кухня
```
Порт сейчас в НА проброшен только 1883.
Подскажите пожалуйста, нужны ли доп. порты?
