### ISSUE TITLE
перестать слушать после локальной команды

### ISSUE THREAD

**Issue by instingt** [AlexxIT/YandexStation#111]
>  Команда всегда отправляется через облако, даже на локальный колонках, потому что это единственно известный способ, чтоб станция НЕ продолжала слушать после TTS.

Нашел способ, что бы колонка перестала слушать после сообщения со спецэффектами в локальном режиме. Для этого сразу после отправки спецэффектов вызываю команду "хватит". Тем самым колонка перестает слушать. 

```
- alias: beep
  trigger: 
    .....
  action:
    - service: media_player.play_media
      entity_id: media_player.yandex_station
      data:
        media_content_id: <speaker audio="alice-sounds-animals-cat-3.opus">
        media_content_type: dialog
    - service: media_player.play_media
      entity_id: media_player.yandex_station
      data:
        media_content_id: хватит
        media_content_type: command
```

Пока работает отлично. Можно пользоваться.
