### ISSUE TITLE
Как получить ответ от той колонки, которой был задан вопрос?

### ISSUE THREAD

**Issue by DivanX10** [AlexxIT/YandexStation#121]
Как сделать так, чтобы отвечала та колонка, у которой спрашивают? Cделал вот так: спрашиваю у одной колонки и получаю ответ, иду спрашивать у другой колонки - тишина. Создал сценарий и прокинул в яндекс, где по просьбе Алисы запускается сценарий

![Снимок](https://user-images.githubusercontent.com/64090632/108263447-58cfea80-7177-11eb-8c06-e2baa7209003.JPG)

Отвечает только одна главная колонка
```
alias: 'Ванная: Стиральная машина. Уведомление. Яндекс Алиса.'
sequence:
  - service: tts.yandex_station_say
    data:
      message: >-
        Оставшееся время стирки {{
        states("sensor.washing_machine_remain_time")}}, Статус стиральной машины
        {{ states("sensor.washing_machine_run_state")}}, Выбранная программа для
        стирки {{ states("sensor.washing_machine_current_course")}}
mode: single
icon: 'mdi:washing-machine'
```

Если я укажу вот таким образом, то будут говорить все колонки, чего мне не нужно.

```
alias: 'Ванная: Стиральная машина. Уведомление. Яндекс Алиса.'
sequence:
  - service: tts.yandex_station_say
    data:
      entity_id:
        - media_player.yandex_station_11111111111111111111
        - media_player.yandex_station_22222222222222222222
      message: >-
        Оставшееся время стирки {{
        states("sensor.washing_machine_remain_time")}}, Статус стиральной машины
        {{ states("sensor.washing_machine_run_state")}}, Выбранная программа для
        стирки {{ states("sensor.washing_machine_current_course")}}
mode: single
icon: 'mdi:washing-machine'
```
