### ISSUE TITLE
Не работают intents

### ISSUE THREAD

**Issue by EropForWork** [AlexxIT/YandexStation#122]
Добрый день. Почему то колонка перестала реагировать на голосовые intents. 
Последовательность что я сделал за пару дней:

1. Установил интеграцию Yandex Dialogs
2. Настроил и заставил работать.
3. Систематизировал файлы в config'e HA. По видео AlexxIT, расфасовал один большой configuration.yaml на много маленьких в папке conf.
4. Так как некоторые старые intents повторяли новые диалоги в Yandex Dialogs, я их удалил. Потому что диалоги и обычные intents обрабатываются одинаково...типо `intents: включи телевизор:` и настроенные диалог с голосовой командой `Алиса, попроси дом включить телевизор` придёт евентом `event_type: yandex_intent`, а в автоматизации у меня расписаны условия на части слов `включ `и `фильм`, чтобы сработал на фильм/фильмы/фильмов и тд...
5. После этого(удаления из файла yaml некоторых intents) как обычно Алиса стала неверно отвечать на обычные intents. То есть например запрос про температуру, а она мне телевизор включит.
6. Удалил все сценарии и intents в устройствах  в приложении Яндекс. Как понятно, с этого момента intents  не работают.
7. Перезагрузил HA
8. Обвил список устройств в приложении Яндекс, добавив intents.
9. Перезагрузил HA
10. Обновил в приложении Яндекса сценарии, они появились.
11. Но на голосовые команды колонка перестала отвечать как запрограммировано. То есть вообще отвязалась от HA.

2 раза переустанавливал все интеграции и тд и тп. Сейчас так:

Интеграции:
- Yandex Smart Home
- Yandex Dialogs
- Yandex.Station

Файл конфигурации:
Путь - ***\config\conf\yandex\yandex.yaml

Код:
```
yandex_smart_home:
  filter:
    include_domains:
      - media_player

yandex_station:
  username: ****
  password: !secret Yandex_Password
  tts_service_name: yandex_station_say
  recognition_lang: ru-RU
  devices:
    *****************:
      host: *********
      name: Яндекс Станция Мини
  intents:
    тест авто: Тест
yandex_dialogs:
  name: Дом
  allowed_user_ids:
    - **************************************************************
```
На голос не реагирует, если нажать на кнопку запуска сценария в приложении Яндекс, то колонка сделает что нужно(и скажет и телик включит).

Что я сделал не так!?(
П.С. Диалоги работают, я могу переписать всё на диалоги, но добавлять в предложение голосом `попроси Дом`, `Узнай у Дома` и тд пока что не хочется.

**Comment by userX32** [comment]
Не уверен как оно должно работать. Но сценарии в яндексе создаются без триггеров.

При создании тестового интента:
```
yandex_station:
  username: !secret yandex_login
  password: !secret yandex_password
  include:
    - Телевизор
    - Кондиционер
  intents:
    Покажи сообщение: ага
```
Создается вот такой сценарий:
![image](https://user-images.githubusercontent.com/11854944/108719117-3f8cbc80-7530-11eb-9e1d-255f21ba01f4.png)

Если вручную ему добавить триггер на фразу "покажи сообщение", что все нормально отрабатывает.
