### ISSUE TITLE
Включить плейлист пользователя

### ISSUE THREAD

**Issue by allmoney** [AlexxIT/YandexStation#15]
В автоматизацию ввёл:

```
  - data:
      entity_id: media_player.yandex_station_040078
      media_content_id: 1008    # ID альбома в Яндекс.Музыка
      media_content_type: playlist  # album, track or playlist
    service: media_player.play_media
```

Но заиграла песня, которой нет в плейлисте... :(
ID плейлиста взял из урла:
https://music.yandex.ru/users/mylogin/playlists/1008

Что не так? Please, help! )
