### ISSUE TITLE
Станция недоступна после отключения электричества. Часть 2

### ISSUE THREAD

**Issue by mr-dxdy** [AlexxIT/YandexStation#204]
Ранее я задавал этот [вопрос](https://github.com/AlexxIT/YandexStation/issues/180). Но проблема так и осталась. После отключения электричества мне нужно самому где-то в настройках HA перезапукскать или yandex station plugin сам это делает?
@dmamontov @AlexxIT  

![](https://sun9-57.userapi.com/impg/vSJtT5C9m61ZCdDpSy-Hc8Q8iS93CvlhPgWISg/4GhD-xr4u1o.jpg?size=727x1600&quality=96&sign=249993486789dec2aaf2f9e7a169ec13&type=album)

**Comment by dmamontov** [comment]
Да, случается иногда такое когда долгий простой. Я обычно пользуюсь сервисом принудительного релоада после того как появляется интернет. О нем писал ранее https://github.com/AlexxIT/YandexStation/issues/180#issuecomment-905389480

**Comment by mr-dxdy** [comment]
@AlexxIT почему pull-request от @dmamontov не попал в master? @dmamontov возможно и правда электричество отключают на большой интервал.

**Comment by almazikv** [comment]
у меня эта проблема стала возникать иногда просто при перезапуске HA. Именно эта интеграция не грузится со ссылкой на то, что нет доступа по сети к quasar.yandex.ru. Причем иногда даже три перезапуска подряд проблему не лечат.
Пришлось вот такую автоматизацию сделать:
```
trigger:
  - platform: homeassistant
    event: start
condition: []
action:
  - delay:
      hours: 0
      minutes: 0
      seconds: 30
      milliseconds: 0
  - service: homeassistant.reload_config_entry
    data:
      entry_id: xxxxxx
```
В принципе сюда же можно в trigger добавить событие когда статус media_player.yandex_station_X становится unavailable

**Comment by AlexxIT** [comment]
В версии 3.6 будет два фикса:
- Добавится отложенная настройка интеграции на случай, если при при старте ХА не будет Интернета, спасибо @dext0r за подсказку. Когда появится интернет - все колонки станут доступны без рестарта ХА
- Добавится поддержка рестарта интеграции из GUI или сервисом

```yaml
service: homeassistant.reload_config_entry
target:
  entity_id: media_player.yandex_station_mini
```
