### ISSUE TITLE
Третий способ вызвать TTS - не работает на нескольких колонках

### ISSUE THREAD

**Issue by bankir82** [AlexxIT/YandexStation#221]
Если вызвать уведомление/оповещение через "третий способ вызвать TTS" и указать несколько колонок, то уведомление будет только на одной из них и при этом рандомно.
Если заменить на media_content_type: dialog, то колонки продолжают слушать и приходится высчитывать по таймеру сколько длится уведомление и ставить задержку, а потом отправлять команду Стоп. (ужасно неудобно, когда приходится менять текст)
Если поставить media_content_type: text, то ограничение в 100 символов.

Вот так работает только 1 колонка и при этом разная, а не первая.
скрипт:
```
yandex_tts_all_text:
    alias: "Уведомление о превышении CO2"
    sequence:
    - service: media_player.play_media
      entity_id: 
      - media_player.yandex_station_1
      - media_player.yandex_station_2
      - media_player.yandex_station_x3
      data:
        media_content_id: "Внимание, высокий уровень цо2, {{ states('sensor.0x00124b00232831e6_co2') }}."
        media_content_type: text:умный дом
```
