### ISSUE TITLE
Ошибка при отправке в Телеграм сообщения от станции

### ISSUE THREAD

**Issue by aatemes** [AlexxIT/YandexStation#225]
Добрый день! 

При ответе в Телеграм с указанием пользователя, инициировавшего запрос, возникает ошибка:

```
2021-12-24 22:00:21 ERROR (MainThread) [homeassistant.components.automation.obshchenie_s_alisoi_cherez_telegu] _Сервер: общение с Алисой через телегу: Error executing script. Invalid data for choose at pos 1: expected int @ data['target'][0]
2021-12-24 22:00:21 ERROR (MainThread) [homeassistant.components.automation.obshchenie_s_alisoi_cherez_telegu] Error while executing automation automation.obshchenie_s_alisoi_cherez_telegu: expected int @ data['target'][0]
```

То есть если я правильно понял, ему не нравится то, что в target при отправке в телегу. 
Если вообще убрать параметр "target", то сообщение отсылается в чат по-умолчанию (первый в конфиге телеги) корректно. 

Сервис вызывается как в примере в документации:
```
id: yandex_telega1
alias: '_Сервер: общение с Алисой через телегу'
trigger:
  - platform: event
    event_type: telegram_text
    id: incoming
  - platform: event
    event_type: yandex_station_response
    id: outgoing
action:
  - choose:
      - conditions:
          - condition: trigger
            id: incoming
        sequence:
          - service: media_player.play_media
            target:
              entity_id: media_player.yandex_station_xkID
            data:
              media_content_id: '{{ trigger.event.data.text }}'
              media_content_type: question:'{{ trigger.event.data.chat_id }}'
      - conditions:
          - condition: trigger
            id: outgoing
        sequence:
          - service: telegram_bot.send_message
            data:
              disable_notification: true
              message: '{{ trigger.event.data.text }}'
              target: '{{ trigger.event.data.request_id }}'
    default: []
mode: parallel
max: 10

```
Пытался по-разному использовать кавычки, а также насильно преобразовать в int через шаблоны jinja, но не преуспел(( 

Ответ станции в "событиях" такой: 
```
{
    "event_type": "yandex_station_response",
    "data": {
        "entity_id": "media_player.yandex_station_xkID",
        "name": "Яндекс Станция Макс",
        "text": "Работник мясокомбината пытался вынести со склада продукцию, но был пойман с потрохами.",
        "request_id": "'776040'"
    },
    "origin": "LOCAL",
    "time_fired": "2021-12-24T19:00:20.929791+00:00",
    "context": {
        "id": "eca63c15a2d4f0ee5e92887a8ea81c65",
        "parent_id": null,
        "user_id": null
    }
}
```

В трассировке автоматизации в "Changed Variables" это выглядит так:
```
trigger:
  id: outgoing
  idx: '1'
  platform: event
  event:
    event_type: yandex_station_response
    data:
      entity_id: media_player.yandex_station_xk0ID
      name: Яндекс Станция Макс
      text: >-
        Работник мясокомбината пытался вынести со склада продукцию, но был
        пойман с потрохами.
      request_id: '''776040'''
    origin: LOCAL
    time_fired: '2021-12-24T19:00:20.929791+00:00'
    context:
      id: eca63c15a2d4f0ee5e92887a8ea81c65
      parent_id: null
      user_id: null
  description: event 'yandex_station_response'
```

Было подозрение, что дело в неожиданно коротком ID в телеге, но с 290625084 то же самое.
