### ISSUE TITLE
Обновлять список покупок молча

### ISSUE THREAD

**Issue by faustlab** [AlexxIT/YandexStation#229]
Было бы хорошо если бы можно было обновлять список покупок с отключенным звуком.
Дома народ пугается если я обновляю список покупок.
попытался обновлять список покупок с параметром **extra**
```
service: media_player.play_media
target:
  entity_id: media_player.yandex_station_мояколонка
data:
  media_content_id: update
  media_content_type: shopping_list
  extra:
    volume_level: 0.1
```
громкость не поменяла.
пока остановился на последовательности:
media_player.volume_set - 0.1 громкость
пауза 3 секунды
media_player.play_media - обновляю список
пауза 60 секунд
media_player.volume_set - 0.8 громкость

**Comment by chertvl** [comment]
Как временное и аналогичное решение, могу предложить сделать самостоятельно аналогичный функционал с помощью input_number и скрипта. Громкость запоминается в инпут, алисе отправляется "стоп" как только она начинает озвучивать список, после чего громкость восстанавливается.

Параметры input_number:
min: 0
max: 1
step: 0.01

```
alias: (Алиса) Обновить список покупок
icon: mdi:cart-arrow-up
sequence:
  - service: input_number.set_value
    target:
      entity_id: input_number.volume_alice
    data:
      value: '{{ state_attr(''media_player.alice'', ''volume_level'')}}'
  - service: media_player.volume_set
    target:
      entity_id: media_player.alice
    data:
      volume_level: 0.01
  - delay:
      milliseconds: 300
  - service: media_player.play_media
    data:
      media_content_id: update
      media_content_type: shopping_list
    target:
      entity_id: media_player.alice
  - delay:
      milliseconds: 300
  - service: media_player.play_media
    target:
      entity_id: media_player.alice
    data:
      media_content_type: command
      media_content_id: стоп
  - delay:
      milliseconds: 300
  - service: media_player.volume_set
    target:
      entity_id: media_player.alice
    data:
      volume_level: '{{ states(''input_number.volume_alice'')}}'
mode: single

```
