### ISSUE TITLE
Нет события типа yandex_station_response

### ISSUE THREAD

**Issue by iStitch07** [AlexxIT/YandexStation#237]
Добрый день
Установил интеграцию из HACS, настраиваю по инструкции.
Дошел до пункта с телеграмм ботом и обнаружил что нет события yandex_station_response
У меня станция лайт

**Comment by AlexxIT** [comment]
Станция работает в локальном режиме, обложки показывает?

**Comment by iStitch07** [comment]
Да, в локальном обложки показывает

**Comment by AlexxIT** [comment]
Событие бывает только в ответ на команду с типом `question`

**Comment by Sa1mon1** [comment]
Думаю схожая проблема у меня также. Алиса не пишет сообщения в телегу, но исправно отвечает и выполняет команды. Обложки есть, локальный режим также. В чате проблема такая у многих была.

**Comment by milkywayfarer** [comment]
Аналогичная проблема, в логах пишет следующее: `Invalid data for call_service at pos 1: expected int @ data['target'][0]` Колонка отвечает на полученную через Telegram команду вслух. Обложки не проверял, локальный способ вызова TTS со всеми эффектами работает. Колонка Lite

**Comment by fintros** [comment]
+1 - команды с "question:" исполняются, но событие "yandex_station_response" не генерится - проверил трейсом на последней версии интеграции. (девайс - Стандартная Яндекс Станция)

**Comment by Sairond** [comment]
+1
Перестало генерироваться событие yandex_station_response.
Переустановка компонента не помогла.

**Comment by loony82361** [comment]
+1
Аналогичная проблема, станция не отвечает в телеграмм и не обновляет список покупок. Обложки показываются. Яндекс Станция самая первая, версия ПО: 2.117.5.13.1321554399.20220526.45

**Comment by malinovsku** [comment]
+1
1 июня так же перестали приходить ответы в yandex_station_response, список покупок не обновляет, обложки при этом показывает.
Так же при вызове команды с типом dialog атрибут alice_state не меняется, когда по факту она говорит или слушает далее, а лишь после быстро обновляет alice_state SPEAKING -> LISTENING -> IDLE.
Проблемы на 2 колонках станции мини первые прошивка на обоих 1.117.4.12.1313282510.20220518
Ошибка по списку покупок:
alice_list = RE_SHOPPING.findall(card['text'])
TypeError: 'NoneType' object is not subscriptable

**Comment by AlexxIT** [comment]
Возможно были проблемы со стороны Яндекса. Сейчас список покупок синхронизируется нормально

**Comment by AlexxIT** [comment]
По `yandex_station_response` также не подтверждаю. Возможно в момент ошибки колонка потеряла локальный режим

**Comment by mr-dxdy** [comment]
Сегодня попробовал алису с телеграммом подружить и опять словил эту ошибку "Алиса отвечает на мое сообщение из телеграмма, но ответ не отправляет в телеграмм".  В логах вот такая ошибка:

```
Error while executing automation automation.automation_22: expected int @ data['target'][0]
```

Версия yandex_station: 3.11.0
Колонка: Лайт
HA: 2022.8.7

Мой скрипт:

```
telegram_bot:
  - platform: polling
    api_key: !secret telegram_bot_api_key
    allowed_chat_ids:
      - !secret telegram_XXXX
      - !secret telegram_YYYY

automation:
  - trigger:
      platform: event
      event_type: telegram_text
    action:
      service: media_player.play_media
      entity_id: media_player.yandex_station_lb0000XXXXXXX
      data:
        media_content_id: "{{ trigger.event.data.text }}"
        media_content_type: "question:{{ trigger.event.data.chant_id }}"
  - trigger:
      platform: event
      event_type: yandex_station_response
    action:
      service: telegram_bot.send_message
      data:
        target: "{{ trigger.event.data.request_id }}"
        message: "{{ trigger.event.data.text }}"
```
