### ISSUE TITLE
Колонка молчит

### ISSUE THREAD

**Issue by Serhioromano** [AlexxIT/YandexStation#251]
Я создал вот такой скрипт

```yaml
say_something:
  alias: Say something
  sequence:
  - service: media_player.play_media
    data:
      media_content_id: проверка
      media_content_type: dialog
    target:
      entity_id: media_player.yandex_station_040000c0999616
      device_id: 2030d74bc7bcee2a98567df84ba
  mode: queued
  icon: mdi:speaker-wireless
  max: 10
```

Но когда я его запускаю ничего не происходит. Тишина. Но если я на дашборде из плеера отправлю фразу сказать то она говорит.

Что я не так сделал¿
