### ISSUE TITLE
Не могу нормально настроит обложку Яндекс Макс

### ISSUE THREAD

**Issue by AntoxaSa** [AlexxIT/YandexStation#275]
```
   - entity: media_player.yandex_station_xk0000000000000764390002449fdcb4
          artwork: full-cover
          sound_mode: icon
          hide:
            sound_mode: false
            runtime: true
          tts:
            platform: yandex_station
          type: 'custom:mini-media-player'
```
![карточка](https://user-images.githubusercontent.com/71827946/171040536-3a9e3bce-e6f8-4619-b7c9-8c246b6274ec.jpg)

Прошу помощи, как сделать корректную карточку с кнопками для Яндекс Макс
