### ISSUE TITLE
В mini media player перестала работать отправка команд. Версия 3.10.0

### ISSUE THREAD

**Issue by DonAlonsoVik** [AlexxIT/YandexStation#277]
При нажатии на кнопку тест или команда, выдаёт:
Не удалось вызвать службу:
media_player/select_sound_mode. Entity media_player.yandex_station_XXXXXX does not support this service.

Остальные кнопки работают. 
до обновления работало, не помню правда предыдущую версию.

Может изменить в коде, что надо, за основу брал с описания, мой код в плеере:
```
type: custom:mini-media-player
entity: media_player.yandex_station_XXXXXX
artwork: cover
sound_mode: icon
tap_action:
  action: url
  url: >-
    ya-search-app-open://path?uri=messenger://call/create/private?device_id=XXXXXX
  new_tab: true
shortcuts:
  attribute: sound_mode
  buttons:
    - icon: mdi:account-voice
      id: Произнеси текст
      type: sound_mode
    - icon: mdi:robot
      id: Выполни команду
      type: sound_mode
    - icon: mdi:playlist-star
      id: включи мою любимую музыку вперемешку
      type: command
    - icon: mdi:playlist-music
      id: включи плейлист дня
      type: command
    - icon: mdi:heart
      id: лайк
      type: command
    - icon: mdi:heart-off
      id: снять лайк
      type: command
  columns: 6
hide:
  sound_mode: true
  runtime: false
tts:
  platform: yandex_station
name: Алиса
```
Спасибо за помощь!
