### ISSUE TITLE
Не работают события yandex.intent

### ISSUE THREAD

**Issue by balonchiks** [AlexxIT/YandexStation#29]
Добрый день, перестали работать события из такой автоматизации:

```
  trigger:
    platform: event
    event_type: yandex_intent
    event_data:
      text: Какая температура в зале
  action:
    - service: tts.alice_say
      entity_id: media_player.yandex_station_xxxxx
      data_template:
        message: "blablabla
```

Еще вчера утром все работало и станция отвечала на мои кастомные команды.

В логах пишет это на любую из автоматизаций с yandex_intent:

`Error executing script. Unexpected error for call_service at pos 1: 0, message='Attempt to decode JSON with unexpected mimetype: text/plain; charset=utf-8', url='https://iot.quasar.yandex.ru/m/user/scenarios/blablabla`

Не подскажите, куда смотреть?

HA версия: 0.110.4, бежит в докере на synology. Версия компонента - последная. yandex smart home - тоже последней версии.
