### ISSUE TITLE
Не озвучивает состояние с сенсора

### ISSUE THREAD

**Issue by Alafalx** [AlexxIT/YandexStation#30]
Я новичек и тольно разбираюсь в теме. Пытаюсь сделать уведомление о состоянии датчика через станцию.мини.
Начал с пробного скрипта: 

```
'1591616034809':
  alias: test. Alisa temp TTS
  sequence:
  - data:
      media_content_id: Температура в комнате {{ states('sensor.temperature_158d000215b167')|round
        }}
      media_content_type: text
    entity_id: media_player.yandex_station
    service: media_player.play_media
```
По итогу Алиса просто зачитывает всю строку включая скобки и назавание сенсора, но данные с него не вытягивает. Я что-то сделал не так?

**Comment by balonchiks** [comment]
если выхотите использовать команды jinja в автоматизации, то вам надо указать параметр data как data_template. в вашем случае просто поменяйте эту строчку:
`  - data:`
на вот это:
`  - data_template:`

**Comment by Alafalx** [comment]
> если вы хотите использовать команды jinja в автоматизации, то вам надо указать параметр data как data_template. в вашем случае просто поменяйте эту строчку:
> ` - data:`
> на вот это:
> ` - data_template:`

Поменял, выдает:
> UndefinedError: 'sensor' is undefined

При этом сделал скрипт для pushover, там такой ошибки нету и отсылает он как со значением "data_template", так и с "data"

**Comment by balonchiks** [comment]
попробуйте сделать как в инструкции:
```

script:
  yandex_tts1:
    alias: TTS зависит от настройки "Режим звука"!
    sequence:
    - service: tts.yandex_station_say
      entity_id: media_player.yandex_station
      data_template:
        message: Температура в комнате {{ states("sensor.temperature_hall")|round }} градуса.
```

то есть в вашем случае так:

```
    sequence:
    - service: media_player.play_media
      entity_id: media_player.yandex_station
      data_template:
        message: Температура в комнате {{ states('sensor.temperature_158d000215b167')|round }}

```
