### ISSUE TITLE
Unsupported cloud media: json

### ISSUE THREAD

**Issue by anklav24** [AlexxIT/YandexStation#302]
I've an error.
Problem happens when I try to use the send_command and media player does not show song covers as well
```
service: yandex_station.send_command
data:
  command: sendText
  text: Повтори за мной "Тестовое уведомление"
  position: 120
  id: 2
  type: artist
  volume: 0.5
```

```
Log Details (WARNING)
This error originated from a custom integration.
Logger: custom_components.yandex_station.media_player
Source: custom_components/yandex_station/media_player.py:933
Integration: Yandex.Station ([documentation](https://github.com/AlexxIT/YandexStation), [issues](https://github.com/AlexxIT/YandexStation/issues))
First occurred: 17:45:50 (10 occurrences)
Last logged: 17:52:44

Unsupported cloud media: json
```

It works fine the last week.
What can I do with it?

My environment
```
Home Assistant 2022.8.2
Supervisor 2022.07.0
Operating System 8.4
Frontend 20220802.0 - latest
Yandex.Station v3.10.1
```
