### ISSUE TITLE
Работа спецэффектов

### ISSUE THREAD

**Issue by pkrasnousov** [AlexxIT/YandexStation#314]
Не могу понять, что я делаю не так при попытке вызвать спецэффекты на ответе алисы
Имеем: ЯСтания Мини
Home Assistant 2022.8.7(в докере, network=host)
Колонка вроде как в локальном режиме(в проигрывателе есть обложка, добавлен static ip в конфиге)
configuration.yaml
```
yandex_station:
  devices:
    LP000000000000347216000032DF7D0E:  # device_id вашей колонки
      host: 192.168.1.20
      name: ЯМини в спальне  # имя можно задать и тут

```

automations.yaml
```
- alias: Доброй ночи
  trigger:
  - platform: event
    event_type: yandex_speaker
    event_data:
      value: Сделай громче на 0!
      entity_id: media_player.yandex_station_lp000000000000347216000032df7f0e
  action:
  - service: media_player.play_media
    target:
        entity_id: '{{ trigger.event.data.entity_id }}'  # ответить той же колонкой
    data:
      media_content_id: смелость sil <[500]> город+а берёт
      media_content_type: text
  mode: single
```
В событиях вроде все отображается верно
```
event_type: yandex_speaker
data:
  instance: text_action
  value: Сделай громче на 0!
  entity_id: media_player.yandex_station_lp000000000000347216000032df7f0e
  name: Алиса в спальне
origin: LOCAL
time_fired: "2022-09-18T13:34:39.522267+00:00"
context:
  id: 01GD8CXRX2PF92WVYRVW8Q87DW
  parent_id: null
  user_id: null
__________________________________________________________________________________

event_type: yandex_speaker
data:
  instance: phrase_action
  value: смелость sil города берёт
  entity_id: media_player.yandex_station_lp000000000000347216000032df7f0e
  name: Алиса в спальне
origin: LOCAL
time_fired: "2022-09-18T13:34:40.344302+00:00"
context:
  id: 01GD8CXSPR6P558DJSTQG5NDA6
  parent_id: null
  user_id: null
```

Но Алиса игнорирует спецэффекты.
Где я затупил?
UPD: простой скрипт тоже спецэффекты в голосе не вызывает
scripts.yaml
```
yandex_tts3:
  alias: TTS c эффектами
  sequence:
  - service: media_player.play_media
    data:
      media_content_id: <speaker audio="alice-sounds-game-win-1.opus"> sil <[500]>
        Объявление погоды на сегодня...
      media_content_type: text
    target:
      entity_id: media_player.yandex_station_lp000000000000347216000032df7f0e
```
