### ISSUE TITLE
Ответ шепотом

### ISSUE THREAD

**Issue by fewdji** [AlexxIT/YandexStation#343]
Добрый день!
У меня есть простой сценарий "Спокойной ночи", который получает сигнал от станции, выключает устройства и проигрывает ответ.
Проблема в том, что если раньше (несколько месяцев назад) после произнесения ключевой фразы для вызова сценария ШЕПОТОМ, Алиса тоже воспроизводила ответ из автоматизации шепотом! Сейчас независимо от варианта произнесения станция всегда отвечает обычным голосом..
Возможно ли каким-нибудь образом вернуть так, как было? Очень неудобно, когда Алиса орёт ночью..

  ```yaml
trigger:
  - platform: event
    event_type: yandex_speaker
    event_data:
      value: Сделай громче на 0!.!
  action:
  # тут пропущены выключения устройств
  - service: media_player.play_media
    data:
      media_content_id: Добренькой ночи!  # чтобы не было бесконечного цикла коверкаю фразу
      media_content_type: command
    target:
      entity_id:
      - media_player.yandex_station_mini
  mode: single
```
![сценарий](https://user-images.githubusercontent.com/13124598/219153723-2f73c16a-78fa-4618-8abc-1c0be9076189.png)
