### ISSUE TITLE
Добавить mac адрес колонок в connections устройств

### ISSUE THREAD

**Issue by malinovsku** [AlexxIT/YandexStation#379]
Возможно ли добавить mac адрес колонок, модулей итп в connections устройств?Так как есть интеграции которые связывают объекты в устройство по mac адресу, например UniFi Network и другие сетевые интеграции, тем самым предоставляя больше возможностей.
https://developers.home-assistant.io/docs/device_registry_index/#manual-registration
Заранее спасибо :)

**Comment by AlexxIT** [comment]
Вообще его неоткуда взять. Но если очень хочется феншуя - можете задать mac вручную в yaml в следующем релизе

```yaml
yandex_station:
  devices:
    DEVICE_ID:
      mac: DEVICE_MAC
```
