### ISSUE TITLE
Проговаривание списки покупок при синхронизации

### ISSUE THREAD

**Issue by H1D** [AlexxIT/YandexStation#387]
При синхронизации списка покупок колонка проговаривает весь список. Это ограничение самой алисы? Кажется будто она насильно громкость меняет. Даже если изначально сделать громкость 0. Не важно как: голосом или скриптами

**Comment by SenMorgan** [comment]
Частично спасает эта автоматизация перед синхронизацией списка покупок. Но все равно иногда Алиса проговаривает его с громкостью больше 5.
```yaml
- repeat:
    while:
      - condition: template
        value_template: "{{ not is_state_attr('media_player.yandex_station', 'volume_level', 0.01) }}"
      - condition: template
        value_template: "{{ repeat.index <= 3 }}"
    sequence:
      - service: media_player.volume_set
        data:
          entity_id: media_player.yandex_station
          volume_level: 0.01
      - delay: 0.5
```
