### ISSUE TITLE
Не работает воспроизведение текста на станции

### ISSUE THREAD

**Issue by urtaevS** [AlexxIT/YandexStation#391]
Код срипта:

```
service: media_player.play_media
data:
  media_content_id: Сейчас позову кушать
  media_content_type: text
target:
  entity_id: media_player.yandex_station_2

```
 Ошибка:
```
Cannot connect to host iot.quasar.yandex.ru:443 ssl:default [Try again]
```
