### ISSUE TITLE
volume_level не работает

### ISSUE THREAD

**Issue by Hipokys** [AlexxIT/YandexStation#397]
Заметил, что автоматизации не управляют громкостью yandex module 2:
- снижение громкости вечером
-  увеличение утром

Использую соответственно:
```
data:
    volume_level: 0.8

data:
    volume_level: 1
```

Через пульт голосом, только: 
громче, тише на 1 пункт +/-
Как раньше - "сделай громкость 5"
не работает, но это понятно, 
Яндекс сменил алгоритм.
