### ISSUE TITLE
Яндекс ТВ станция про громкость

### ISSUE THREAD

**Issue by voron92** [AlexxIT/YandexStation#402]
Адекватно не регулируется громкость на телевизоре, при нажатии на уровень громкости примерно по середине шкалы, громкость на телевизоре становится равной 100%, громкость регулируется в пределах от 1 до 10, в то время как шкала в карточке имеет 100 делений громкости, если ставишь громкость например 11, громкость на телевизоре становится 100%.
Думаю дело в том что на обычных колонках 10 уровней громкости, а на тв станции 100.

**Comment by Hipokys** [comment]
`
yandex_volume.yaml
-------------------------------
input_number:
  hall_volume:
    name: Громкость Hall
    #initial: 100
    min: 20
    max: 100
    step: 20
  kitchen_volume:
    name: Громкость Kitchen
    #initial: 100
    min: 20
    max: 100
    step: 20
  yandex_tv_volume:
    name: Громкость Yandex TV
    #initial: 100
    min: 20
    max: 100
    step: 20


automation:
  - alias: "Hall Volume"
    trigger:
      - platform: state
        entity_id: input_number.hall_volume
        to:
    action:
      - service: media_player.play_media
        entity_id: media_player.yandex_module_1
        data:
          media_content_id: Громкость модуль "{{ trigger.to_state.state | int }}"
          media_content_type: command
      - service: media_player.play_media
        entity_id: media_player.yandex_module_1
        data:
          media_content_id: громкость модуля "{{ trigger.to_state.state | int }}"
          media_content_type: text

  - alias: "Kitchen Volume"
    trigger:
      - platform: state
        entity_id: input_number.kitchen_volume
        to:
    action:
      - service: media_player.play_media
        entity_id: media_player.yandex_module_2
        data:
          media_content_id: Громкость модуль "{{ trigger.to_state.state | int }}"
          media_content_type: command
      - service: media_player.play_media
        entity_id: media_player.yandex_module_2
        data:
          media_content_id: громкость модуля "{{ trigger.to_state.state | int }}"
          media_content_type: text

  - alias: "Yandex TV Volume"
    trigger:
      - platform: state
        entity_id: input_number.yandex_tv_volume
        to:
    action:
      - service: media_player.play_media
        entity_id: media_player.yandex_tv
        data:
          media_content_id: Громкость модуль "{{ trigger.to_state.state | int }}"
          media_content_type: command
      - service: media_player.play_media
        entity_id: media_player.yandex_tv
        data:
          media_content_id: громкость телевизора "{{ trigger.to_state.state | int }}"
          media_content_type: text
-------------------------------
`

**Comment by AlexxIT** [comment]
Без физического доступа к устройству не смогу такое починить. Может кто-то из владельцев сможет

**Comment by Hipokys** [comment]
Могу предоставить информационную выборку с 2 модулей и 1 tv.

**Comment by voron92** [comment]
Могу так же дать необходимые файлы, adb доступ настроен

**Comment by AlexxIT** [comment]
Чинить такие вещи вслепую отнимает очень много сил

**Comment by Hipokys** [comment]
Разобрался

**Comment by Hipokys** [comment]
Все, вопрос для меня снят.
```
input_number:
  hall_volume:
    name: Громкость Hall
    #initial: 100
    min: 0
    max: 100
    step: 10


automation:
  - alias: "Hall Volume"
    trigger:
      - platform: state
        entity_id: input_number.hall_volume
        to:
    action:
      - service: media_player.volume_set
        data:
          entity_id: media_player.yandex_module_1
          volume_level: "{{ trigger.to_state.state | int / 1000 }}"
```
