### ISSUE TITLE
Проблемы с интеграцией Conversation

### ISSUE THREAD

**Issue by JampireX** [AlexxIT/YandexStation#433]
Указанный в описанный способ, похоже, устарел и не работает.

В конфиг добавлено:
```
conversation:
  intents:
    media_player.yandex_station_.......: [.+]
```

Чат в интерфейсе появляется, но на любой ввод отвечает ошибкой no_intent_match
```
intent:
  engine: homeassistant
  language: ru
  intent_input: привет
  conversation_id: null
  device_id: null
  done: true
  intent_output:
    response:
      speech:
        plain:
          speech: Прошу прощения, обращение не распознано
          extra_data: null
      card: {}
      language: ru
      response_type: error
      data:
        code: no_intent_match
    conversation_id: null
```

Поскольку в HA завезли нормальную интеграцию ассистентов, может есть возможность ее попробовать реализовать?
