### ISSUE TITLE
Автоматически не отображаются сенсоры (voltage,  power, amperage) от Яндекс розетки

### ISSUE THREAD

**Issue by MikhailTeddy** [AlexxIT/YandexStation#438]
После обновления на HA 2024 больше не получаю данных по напряжению и току с яндекс розетки.
Использовал такой конфиг для получения данных:
```
    sensors:
      rozetka_voltage:
        friendly_name: "Напряжение"
        unit_of_measurement: V
        value_template: "{{ state_attr('switch.rozetka','voltage')}}"
      rozetka_power:
        friendly_name: "Мощность"
        unit_of_measurement: W
        value_template: "{{ state_attr('switch.rozetka','power')}}"
      rozetka_amperage:
        friendly_name: "Ток"
        unit_of_measurement: A
        value_template: "{{ state_attr('switch.rozetka','amperage')}}"
```
