### ISSUE TITLE
Как включить плейлист вперемешку в тихом режиме?

### ISSUE THREAD

**Issue by KAPACb1988** [AlexxIT/YandexStation#446]
Здравствуйте, Как включить нужный мне плейлист вперемешку, и чтобы Алиса не говорила "включаю плейлист....." просто начала играть и все? Посмотрел раздел "чтобы команда бесшумно ушла в ХА", но толи это не то, толи я не понял как ее применить..
Могу включить бесшумно плейлист к примеру так:

```
service: media_player.play_media
target:
  entity_id: media_player.stanciya_spalnya
data:
  media_content_id: тут ссылка на плейлист
  media_content_type: text

```

но что нужно добавить, чтобы воспроизводилось вперемешку, а не по порядку?

**Comment by TonTon-Macout** [comment]
плюсую, тоже непонятно!

**Comment by TonTon-Macout** [comment]
короче походу это сделать невозможно. 
пока сделал так - уменьшаю громкость в 0, отправляю - включи плейлист вперемешку - жду 3 секунды и ставлю нужную громкость.

**Comment by TonTon-Macout** [comment]
с ожиданием как оказалась фигня получается, либо надо ставить большую задержку либо иногда не успевает 
с ожиданием триггера вроде норм работает: 
```
wait_for_trigger:
  - platform: state
    entity_id:
      - media_player.yandex_station
    attribute: alice_state
    to: IDLE
```

**Comment by KAPACb1988** [comment]
Так делал, но все равно это ожидание.. мы не затыкаем Алису, а просто mute как бы включаем, пока она говорит, музыка заиграет только через несколько секунд. Вот в примере в 1ом сообщении музыка сразу играет, но не в случайном порядке. Есть функция shuffle в ha, но она к сожалению тут не работает, она для определенных сервисов применяется.

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/YandexStation/releases/tag/v3.18.1

**Comment by TonTon-Macout** [comment]
такс, а может появилась возможность как-то чтобы на такую команду 
```
service: media_player.play_media
data:
  media_content_id: "Включи релакс музыку вперемешку"
  media_content_type: command
target:
  device_id: cac240243dd
```
алиса молча включала? 
плейлист как то не очень хочется
