### ISSUE TITLE
Перестало срабатывать событие yandex_station_response

### ISSUE THREAD

**Issue by Spirituss** [AlexxIT/YandexStation#466]
При вызове команды media_content_type: question событие yandex_station_response не возникает, нет возможности узнать ответ Алисы. 
Бета не подключалась, ХА не обновлялся.

**Comment by alexxx113** [comment]
И у меня, но подключена бета.
26 февраля последний раз сработала автоматизация

**Comment by AlexxIT** [comment]
Поправлено в мастер версии

**Comment by alexxx113** [comment]
Спасибо!!! Все заработало!

**Comment by alexxx113** [comment]
Поработало 2 дня и больше не работает.
с 7 марта не работает

**Comment by AlexxIT** [comment]
Вы уверены, что пользуетесь мастер версией?

**Comment by alexxx113** [comment]
Вчера скачал и закинул в мастер версию через проводник .
У меня подключена бета, может с этим связано

**Comment by DieMetRik** [comment]
Тоже не работает.
Отправляю вопрос из телеги, запрос уходит
Раньше сразу приходит в телегу ответ
Сейчас тишина

**Comment by urtaevS** [comment]
У себя тоже обнаружил данную проблему.
Версия компонента - 3.13.2

Версия HA:
Core - 2024.3.1
Supervisor - 2024.03.0
Operating System - 12.1

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/YandexStation/releases/tag/v3.13.3

**Comment by alexxx113** [comment]
не заработало
да список покупок работает, а yandex_station_response нет

```
alias: Новый скрипт
sequence:

  - service: media_player.play_media
    data:
      media_content_type: question:1
      media_content_id: Какие будильники?
    target:
      entity_id: media_player.XXXX
```



```
2024-04-01 02:21:30.343 DEBUG (MainThread) [custom_components.yandex_station.core.yandex_glagol] Станция Мини Спальня => local | {'command': 'sendText', 'text': 'какие будильники'}
2024-04-01 02:21:30.990 DEBUG (MainThread) [custom_components.yandex_station.core.yandex_glagol] Response error: 'output_speech'
2024-04-01 02:21:30.993 DEBUG (MainThread) [custom_components.yandex_station.core.yandex_station] Станция Мини Спальня | Empty response on request: 1688
```
