### ISSUE TITLE
Большие станции не видят медиаплееры из configuration.yaml

### ISSUE THREAD

**Issue by ans002** [AlexxIT/YandexStation#467]
Добрый день!
Станции Макс и Макс зигби практически никогда не подхватывают медиаплееры прописанные в 

configuration.yaml:
```
yandex_station:
  media_players:
    - entity_id: media_player.wiim_plus
      name: Wiim plus
      #speaker_id: [media_player.yandex_station_xXXxxxxxxxxxXxxx]
    - entity_id: media_player.wiim
      name: Wiim
    - entity_id: media_player.wiim_mini_4fa8
      name: Wiim mini
```
После N-ной перезагрузки ХА плееры появляются, но при следующей опять пропадают.
При этом станции миди и мини - всегда всё ОК с этим.
С другими плеерами (не WiiM) та же ситуация. Пробовал ТВ добавлять, и.т.д.

P.S.  Протестирована работа с WiiM Pro, WiiM Pro +, и ДАЖЕ WiiM mini. Работает отлично, наконец то получил 
шикарный по качеству звук (ну насколько он может быть хорошим при mp3 - 320) при полном управлении голосом.
WiiM mini по dlna. Остальные по chromecast.
Стриммеры выдают битпрефект. т.е нормальный 44,1. До этого пытался через телевизоры, медиаплееры с хромкаст, 
всегда была передискретизация до 48 КГц - и в итоге "каша". Спасибо огромное за труды!  Вылечить бы еще большие 
станции, было бы супер!
![2024-02-29_19-29-05](https://github.com/AlexxIT/YandexStation/assets/144158709/284b2c71-01fe-4c45-b3cc-93f4c094c465)
![2024-02-29_19-29-24](https://github.com/AlexxIT/YandexStation/assets/144158709/a84b2500-01ae-4d60-882f-55aec5074b6c)
![2024-02-28_14-32-33](https://github.com/AlexxIT/YandexStation/assets/144158709/9e8b2148-16a6-4d9c-bb05-9090068fe2a2)
