### ISSUE TITLE
Проблема при синхронизации списка покупок 

### ISSUE THREAD

**Issue by w00dwind** [AlexxIT/YandexStation#480]
**Core 2024.3.3
Supervisor 2024.03.0**

При запуске следующего скрипта: 

```
alias: Обновить список покупок
sequence:
  - service: media_player.play_media
    entity_id: media_player.# Тут указан id моей колонки
    data:
      media_content_id: update
      media_content_type: shopping_list
```
Получаю ошибку: 

`Failed to call service script/update_shopping_list. 'NoneType' object is not subscriptable`

Товары добавляются в список Алисы, но не попадают в список HA
