### ISSUE TITLE
Не настраивается внешний датчик температуры для кондиционера после обновления до 3.14.1

### ISSUE THREAD

**Issue by lmorningstar116** [AlexxIT/YandexStation#488]
В конфиге
```yaml
yandex_station:
  include:
    - name: Кондиционер
      current_temperature: "{{ states('sensor.temperatura_spalnia_temperature') }}"
```
В интеграции задублирован кондиционер
![image](https://github.com/AlexxIT/YandexStation/assets/47708963/5a595205-90ed-4b63-992a-48410686ae8f)
Один без объектов
![image](https://github.com/AlexxIT/YandexStation/assets/47708963/98499a47-cb0c-4794-beb2-3003d23f69fd)
