### ISSUE TITLE
При переключении  в конфиге на ui-lovelace.yaml перестает работать компонент yandex_station

### ISSUE THREAD

**Issue by hkajarov** [AlexxIT/YandexStation#51]
Установил компоненту yandex_station, работает прекрасно пока не переключаю на "ручную lovelace" заданием в configuration.yaml:
```
lovelace:
  mode: yaml
```
При этом а же компонента gismeteo bp custom_components подхватывается

**Comment by 2andr** [comment]
Подниму вопрос. У меня тоже lovelace в режиме yaml
Как получить доступ к компоненту?

**Comment by 2andr** [comment]
Вот например вкладка для станции
```
  - title: Яндекс Станция
    icon: yandex:alisa
    
    cards:
    
      - type: vertical-stack
        cards:
        - type: markdown
          content: >
             **Яндекс Станция**     

        - type: entities
          title: Команды станции
          show_header_toggle: false
          entities:
             - entity: script.yandex_tts2
               name: Сервис уведомлений
             - entity: media_player.yandex_station_**уникальный*Id*станции**
               artwork: full-cover
               sound_mode: icon
               hide:
                 sound_mode: false
                 runtime: false
               tts:
                 platform: yandex_station
                 type: 'custom:mini-media-player'             

```
