### ISSUE TITLE
Добавить влажность кондиционерам

### ISSUE THREAD

**Issue by Mrboob58** [AlexxIT/YandexStation#513]
![climate](https://github.com/AlexxIT/YandexStation/assets/46161497/6a119eda-611f-4f10-9e7b-ff69c93699c0)
Давно заметил, что кондиционер имеет нулевое значение в "current_temperature: null" - это как-то можно пофиксить?
Или брать значение вообще из другого датчика...

**Comment by PiratesGhost** [comment]
> брать значение вообще из другого датчика...

Ответ есть в [документации](https://github.com/AlexxIT/YandexStation#:~:text=%22%7B%7B%20states(%27-,sensor.temperature,-%27)%20%7D%7D%22%20%20%20%23).

```
yandex_station:
  include:
    - name: Кондиционер
      current_temperature: "{{ states('sensor.temperature') }}" 
```
вместо sensor.temperature - указать свой другой датчик.
