### ISSUE TITLE
Перестала говорить шепотом в media_content_type: text

### ISSUE THREAD

**Issue by sashayohan** [AlexxIT/YandexStation#521]
```
service: media_player.play_media
data:
  entity_id: media_player.yandex_station_livingroom
  media_content_type: text
  media_content_id: <speaker is_whisper='true'>Текст
```
сегодня заметил что перестала говорить шепотом, теперь произносит как есть - "speaker is whisper true Текст"
media_content_type: dialog - произносит шепотом
media_content_type: command - у меня и раньше никогда не отвечала шепотом на команду
