### ISSUE TITLE
Единицы измерения

### ISSUE THREAD

**Issue by booroondook-eng** [AlexxIT/YandexStation#524]
Помогите, пожалуйста, разобраться с единицами измерения датчиков, прокинутых из Home Assistant. Почему-то УДЯ любое давление отображает в мм рт.ст., а любую температуру - в градусах Цельсия.
С температурой ладно - собственно, градлусами Цельсия и так пользуемся, поэтому как бы проблемы не возникает.
А вот с давлением проблема.
Есть датчик давления воды (внимание - не атмосферного давления, а воды в трубопроводе. Он должен выдавать давление в барах (bar). В ХА, собственно, так и настроено:
![2024-07-25 23 21 28](https://github.com/user-attachments/assets/4bc49539-b47a-408b-bde3-cb609b97d63c)
Для прокидывания в УДЯ имеется следующая запись в yaml-файле:
```
      sensor.sensor_hub_heating_water_pressure:
        name: Система отопления
        properties:
          - type: pressure
            entity: sensor.sensor_hub_heating_water_pressure
            unit_of_measurement: bar

```
Однако УДЯ показывает давление в миллиметрах ртутного столба, конвертируя его из величины в барах
![2024-07-25 23 27 05](https://github.com/user-attachments/assets/0c27d82d-94c8-4c80-993a-ddf7eb929fbc)
Пробовал убирать из конфигурации строчку с единицей измерения - никаких изменений не происходит!

P.S. Ну и пресловутые (потому что вопрос, кажется уже поднимался) милливольты.
Есть куча датчиков, работающих от батареек. В ХА настроено выдавать напряжение в милливольтах. Однако УДЯ считает милливольты вольтами и даже не конвертирует их, как в случае с давлением. Бывает, спросишь Алису "Что с погодой на улице?", а она и отвечает "напряжение две тысячи девятьсот вольт"!
