### ISSUE TITLE
При синхронизации списка покупок не происходит событие shopping_list_updated

### ISSUE THREAD

**Issue by rlobanov** [AlexxIT/YandexStation#538]
При синхронизации списка покупок не происходит событие shopping_list_updated. 
Настроена синхронизация списка покупок, однако при вызове 
```
- service: media_player.play_media
  entity_id: media_player.yandex_station (моя колонка)
  data:
    media_content_id: update
    media_content_type: shopping_list
```
список синхронизируется, а событие shopping_list_updated не происходит. Таким образом невозможно использовать автоматизацию при обновлении списка покупок. При этом если в списке покупок ХА что то добавить или удалить через интерфейс ХА событие shopping_list_updated срабатывает корректно.

Пример:
Голосом на колонке говорю: "Алиса, добавь хлеб в список покупок". Она добавляет в свой список покупок.
Далее вызывается служба (на момент тестирования раз в 10 минут) media_player.play_media с контентом update shopping_list.
Хлеб добавляется в список товаров ХА, однако событие shopping_list_updated  не произошло.
При удалении позиций через Алису, так же не происходит вызова события shopping_list_updated. 

Каким образом можно заставить ХА уведомлять о добавленных позициях в список покупок?
