### ISSUE TITLE
Пропала строка ввода произносимого текста в карточке медиаплеера(

### ISSUE THREAD

**Issue by kirillec** [AlexxIT/YandexStation#548]
Пропала строка ввода произносимого текста в медиаплеере(
Использую кастомный медиаплеер "mini-media-player" из вашего же примера с вашими же кодом вловлейс, и всё было отлично, но куда-то пропала строка ввода текста(Кнопкаотправить есть, а вот куда вводить текст нету(

![Снимок](https://github.com/user-attachments/assets/b1d6f2a8-8534-4faf-92c2-823a56c974b5)

```
      - type: 'custom:mini-media-player'
        entity: media_player.yandex_station_ff98f0296d3325df93cce40f  # поменяйте на вашу колонку
        artwork: cover
        sound_mode: icon
        shortcuts:
          attribute: sound_mode
          buttons:
            - icon: 'mdi:account-voice'
              id: Произнеси текст
              type: sound_mode
            - icon: 'mdi:robot'
              id: Выполни команду
              type: sound_mode
            - icon: 'mdi:playlist-star'
              id: включи мою любимую музыку вперемешку
              type: command
            - icon: 'mdi:playlist-music'
              id: включи плейлист дня
              type: command
            - icon: 'mdi:heart'
              id: лайк
              type: command
            - icon: 'mdi:heart-off'
              id: снять лайк
              type: command
          columns: 6
        hide:
          sound_mode: true
          runtime: false
        tts:
          platform: yandex_station
```

Не подскажите что нужно сделать/дописать чтоб появилась?
