### ISSUE TITLE
Караоке + стриминг

### ISSUE THREAD

**Issue by shurakenas** [AlexxIT/YandexStation#565]
Есть ли возможность передать на ТВ андроид караоке и звук одновременно?

**Comment by AlexxIT** [comment]
#547

**Comment by shurakenas** [comment]
> #547

Думаю, что вы неправильно меня поняли. Если выбрать source мой андроид ТВ в карточке Mini Media Player, то звук будет играть на ТВ, а если после этого отправить поток с текстом:
```
alias: Включить караоке на ТВ
sequence:
  - service: media_player.play_media
    target:
      entity_id: media_player.mibox
    data:
      media_content_id: >-
        http://192.168.1.123:8123/api/camera_proxy_stream/camera.hall_speaker_lyrics?token={{ state_attr('camera.hall_speaker_lyrics', 'access_token') }}
      media_content_type: image/jpeg
```
то на ТВ будет только текст, без звука, ну оно и понятно, ведь оно заменяет предыдущий поток.

Вопрос в том, возможно ли одновременно отправить поток и звука и текста на ТВ?
