### ISSUE TITLE
Процедура авторизации с 2-х факторной аутентификацией

### ISSUE THREAD

**Issue by sochkasov** [AlexxIT/YandexStation#60]
В документации описано как указать учетные данные для подключения к Yandex. А так-же то, что каким-то образом можно использовать аккаунт, где включена 2-х факторная аутентификация. 

```
Двухфакторная авторизация работает по одноразовому паролю из приложения Яндекс.Ключ. Главное успеть за 30 секунд :)

yandex_station:
  username: myuser
  password: mypass
```

Но не сказано как это сделать. Можете рассказать подробнее?
