### ISSUE TITLE
Не всегда получается активировать проброшенный девайс из УДЯ в HA

### ISSUE THREAD

**Issue by fiass** [AlexxIT/YandexStation#630]
### Ошибка: Device action failed: ClientConnectorError(ConnectionKey(host='iot.quasar.yandex.ru', port=443, is_ssl=True, ssl=True, proxy=None, proxy_auth=None, proxy_headers_hash=None), ConnectionRefusedError(111, "Connect call failed ('0.0.0.0', 443)"))

Вызывается из под автоматизации
```
id: '1738528551937'
alias: Авто-свет в прихожей (Вкл)
description: ''
triggers:
  - type: occupied
    device_id: bed34b9435feb9b987862eb44f880edc
    entity_id: 3e775c130836e61af999f1887306cd45
    domain: binary_sensor
    trigger: device
conditions: []
actions:
  - type: turn_on
    device_id: da5317aa508424517b2831352df2b0b4
    entity_id: 16c24be2966be493e7621a1b569808ab
    domain: light
mode: single
```

Иногда она вызывается, иногда нет, дело случая, т.е. повторив автоматизацию через минуту она может сработать а может также выдать эту ошибку в трассировке автоматизации. в локальной сети у лампочки статичный адрес, лампочка от Yandex
```
Yandex:
YNDX-00018
Версия программного обеспечения: 1.0.7
Версия аппаратного обеспечения: 3.0 
--
YandexStation:
Версия 3.18.2
--
HA:
Core 2025.2.1
Supervisor 2025.02.0
Operating System 14.2
Пользовательский интерфейс 20250205.0
```
