### ISSUE TITLE
Lossless

### ISSUE THREAD

**Issue by taravasya** [AlexxIT/YandexStation#643]
Приветствую! Есть уже довольно много треков на я.музыке в lossless сжатии. Однако, сколько не проверял в отладчике, постоянно вижу, что на рендерер прилетает mp3. Проверял DLNA и ChromeCast. Пробовал добавить в configuration.yaml настройки:

```
yandex_station:
  media_players:
    - entity_id: media_player.lyngdorf_3
      name: Lyng1120
      quality: lossless
      codecs: flac
```

После перезапуска HA, в выборе плеера остаётся только HDMI + Lyng1120 (значит настройки применяются)
Однако играет всё равно только mp3
