### ISSUE TITLE
Пропал статус, наименование и другие метаданные по проигрываемой музыке в Media Player

### ISSUE THREAD

**Issue by QuaiGoner** [AlexxIT/YandexStation#649]
Скриншот:

![Image](https://github.com/user-attachments/assets/246f3711-1e61-404b-ab19-802a9eff3a6d)

В то же время управление (старт/пауза) - работают как и другие части интеграции.
Думал проблема в Pi-Hole но и при отключении блокировки - статуса нет.

**Comment by AlexxIT** [comment]
Значит поломался локальный доступ. Иногда помогает перезагрузка колонки. Иногда перезагрузка всего остального.

**Comment by QuaiGoner** [comment]
Сори за пост в закрытый тикет, но даже после добавления в конфигу:

```
yandex_station:
  devices:
    L00T7B600DEEKB:  # device_id вашей колонки
      host: 192.168.0.34
      name: Яндекс Лайт Red  # имя можно задать и тут
```

Не пофиксилось. 

Адрес - статика, ID - из приложения Яндекса
