### ISSUE TITLE
Перестал работать Yandex модуль

### ISSUE THREAD

**Issue by anklimov** [AlexxIT/YandexStation#65]
Изначально, интеграция успешно работала для Яндекс модуля
Модуль работает совместно с колонкой Ellari, функцию выполняет, колонка нормально интегрирована в HA

Пытался прописать модуль в конфиге в формате

```
yandex_station:
  username: xxx
  password: yyy
  devices:
    210d84009e........efcbbc8f07dab0:  # device_id вашей колонки
      host: 192.168.88.ZZ
      name: Яндекс Модуль  # имя можно задать и тут
```

обьект не появляется, никаких аномалий в логах HA не отмечено 

В мультикаст обмене, тем не менее, Модуль себя успешно анонсирует по MDNS%

```
192.168.88.ZZ.mdns > 224.0.0.251.mdns: 0 [2q] [2n] ANY (QM)? ZZ.88.168.192.in-addr.arpa. ANY (QM)? yandex-module-210d8400..........efcbbc8f07dab0.local. (132)

192.168.88.ZZ.mdns > 224.0.0.251.mdns: 0*- [0q] 5/0/0 (Cache flush) TXT "deviceId=210d8400..........efcbbc8f07dab0" "platform=yandexmodule", PTR YandexIOReceiver-210d8400..........efcbbc8f07dab0._yandexio._tcp.local., (Cache flush) SRV yandex-module-210d8400..........efcbbc8f07dab0.local.:1961 0 0, (Cache flush) A 192.168.88.ZZ, PTR _yandexio._tcp.local. (292)
```

Home Assistant 0.116.4
Yandex Station v 2.2.10
