### ISSUE TITLE
Не работают триггеры на yandex_scenario

### ISSUE THREAD

**Issue by mkocdemko** [AlexxIT/YandexStation#660]
Добрый день, перестали срабатывать триггеры по событиям типа yandex_speaker и yandex_scenario, ни с того ни с сего, обновление HOAS не делал, просто отказалась с утра выполнять команды по уборке дома.

```
alias: Кухня Уборка
description: мойка пола кухни
triggers:
  - event_type: yandex_scenario
    event_data:
      value:
        text: Кухня будет вылизана!
    trigger: event
conditions: []
actions:
  - action: script.custom_mode_on
    metadata: {}
    data: {}
  - action: xiaomi_miot.call_action
    data:
      entity_id: vacuum.xiaomi_d110ch_b6d2_robot_cleaner
      siid: 4
      aiid: 1
      params:
        - piid: 1
          value: 18
        - piid: 10
          value: "{\"selects\":[[7,1,1,1,1]]}"
      force_params: true
mode: single
```
Что можно попробовать предпринять? как "перезагрузить" интгерацию? Перезагрузка home assistant ничего не дает. Спасибо.

**Comment by mkocdemko** [comment]
UPD2: даже яндекс scenario не ловил триггеры, в отадке нашел то, что изменились данные в событии и стало не 👍 

```
value: 
         text: ничего не делай
```

а просто надо изменить на 

`value: ничего не делай`

yandex_scenario вообще перестали возращать какие-либо данные в режиме отладки,. пришлось заменять на yandex_speaker

**Comment by jokombo** [comment]
Подтверждаю. Проблема с отработкой триггеров по событиям yandex_scenario. Обнаружил вчера одновременно с ошибкой 400. Меняю на yandex_speaker, работает.

**Comment by lonerr** [comment]
Аналогичная проблема, события типа `yandex_scenario` перестали прилетать, помогло только переключение на `yandex_speaker`.

**Comment by telenkovi** [comment]
Не знаю что и как, но у меня не работает в сценариях медиа плеер воспроизвести  текст- вылетает ошибка.

**Comment by avlapeto** [comment]
Тоже самое. Началось примерно неделю назад. Евенты `yandex_scenario`  просто не тригерятся. При произнесении ключевых фраз тригерится только следующие эвенты:

1)

```
event_type: state_changed
data:
  entity_id: media_player.yandex_station_mg0000000000000016420000323c6fa2
  old_state:
    entity_id: media_player.yandex_station_mg0000000000000016420000323c6fa2
    state: idle
    attributes:
      sound_mode_list:
        - Произнеси текст
        - Выполни команду
      volume_level: 0.45
      is_volume_muted: false
      sound_mode: Произнеси текст
      entity_picture_local: null
      alice_state: IDLE
      friendly_name: Станция Мини new 6fa2
      supported_features: 511885
    last_changed: "2025-06-04T07:31:23.141476+00:00"
    last_reported: "2025-06-04T08:06:52.094314+00:00"
    last_updated: "2025-06-04T08:06:52.094314+00:00"
    context:
      id: 01JWWZN4DYND3B64DS6EZ9S72E
      parent_id: null
      user_id: null
  new_state:
    entity_id: media_player.yandex_station_mg0000000000000016420000323c6fa2
    state: idle
    attributes:
      sound_mode_list:
        - Произнеси текст
        - Выполни команду
      volume_level: 0.45
      is_volume_muted: false
      sound_mode: Произнеси текст
      entity_picture_local: null
      alice_state: LISTENING
      friendly_name: Станция Мини new 6fa2
      supported_features: 511885
    last_changed: "2025-06-04T07:31:23.141476+00:00"
    last_reported: "2025-06-04T08:08:12.840019+00:00"
    last_updated: "2025-06-04T08:08:12.840019+00:00"
    context:
      id: 01JWWZQK98THEHRV3TYHS0JGDE
      parent_id: null
      user_id: null
origin: LOCAL
time_fired: "2025-06-04T08:08:12.840019+00:00"
context:
  id: 01JWWZQK98THEHRV3TYHS0JGDE
  parent_id: null
  user_id: null
```
2) 
```
event_type: state_changed
data:
  entity_id: media_player.yandex_station_mg0000000000000016420000323c6fa2
  old_state:
    entity_id: media_player.yandex_station_mg0000000000000016420000323c6fa2
    state: idle
    attributes:
      sound_mode_list:
        - Произнеси текст
        - Выполни команду
      volume_level: 0.45
      is_volume_muted: false
      sound_mode: Произнеси текст
      entity_picture_local: null
      alice_state: LISTENING
      friendly_name: Станция Мини new 6fa2
      supported_features: 511885
    last_changed: "2025-06-04T07:31:23.141476+00:00"
    last_reported: "2025-06-04T08:08:12.840019+00:00"
    last_updated: "2025-06-04T08:08:12.840019+00:00"
    context:
      id: 01JWWZQK98THEHRV3TYHS0JGDE
      parent_id: null
      user_id: null
  new_state:
    entity_id: media_player.yandex_station_mg0000000000000016420000323c6fa2
    state: idle
    attributes:
      sound_mode_list:
        - Произнеси текст
        - Выполни команду
      volume_level: 0.45
      is_volume_muted: false
      sound_mode: Произнеси текст
      entity_picture_local: null
      alice_state: BUSY
      friendly_name: Станция Мини new 6fa2
      supported_features: 511885
    last_changed: "2025-06-04T07:31:23.141476+00:00"
    last_reported: "2025-06-04T08:08:16.106144+00:00"
    last_updated: "2025-06-04T08:08:16.106144+00:00"
    context:
      id: 01JWWZQPFAA216WSC6X8A8QZKM
      parent_id: null
      user_id: null
origin: LOCAL
time_fired: "2025-06-04T08:08:16.106144+00:00"
context:
  id: 01JWWZQPFAA216WSC6X8A8QZKM
  parent_id: null
  user_id: null
```

3)
```
event_type: state_changed
data:
  entity_id: media_player.yandex_station_mg0000000000000016420000323c6fa2
  old_state:
    entity_id: media_player.yandex_station_mg0000000000000016420000323c6fa2
    state: idle
    attributes:
      sound_mode_list:
        - Произнеси текст
        - Выполни команду
      volume_level: 0.45
      is_volume_muted: false
      sound_mode: Произнеси текст
      entity_picture_local: null
      alice_state: BUSY
      friendly_name: Станция Мини new 6fa2
      supported_features: 511885
    last_changed: "2025-06-04T07:31:23.141476+00:00"
    last_reported: "2025-06-04T08:08:16.106144+00:00"
    last_updated: "2025-06-04T08:08:16.106144+00:00"
    context:
      id: 01JWWZQPFAA216WSC6X8A8QZKM
      parent_id: null
      user_id: null
  new_state:
    entity_id: media_player.yandex_station_mg0000000000000016420000323c6fa2
    state: idle
    attributes:
      sound_mode_list:
        - Произнеси текст
        - Выполни команду
      volume_level: 0.45
      is_volume_muted: false
      sound_mode: Произнеси текст
      entity_picture_local: null
      alice_state: SPEAKING
      friendly_name: Станция Мини new 6fa2
      supported_features: 511885
    last_changed: "2025-06-04T07:31:23.141476+00:00"
    last_reported: "2025-06-04T08:08:17.107565+00:00"
    last_updated: "2025-06-04T08:08:17.107565+00:00"
    context:
      id: 01JWWZQQEK3W4F5PQPGB88N0V7
      parent_id: null
      user_id: null
origin: LOCAL
time_fired: "2025-06-04T08:08:17.107565+00:00"
context:
  id: 01JWWZQQEK3W4F5PQPGB88N0V7
  parent_id: null
  user_id: null
```

При запуске мультимедиа или чтения текста из HA - работает.

<img width="522" alt="Image" src="https://github.com/user-attachments/assets/f37e5c4d-30d5-49a3-9a32-7041b9cf582e" />
