### ISSUE TITLE
На 3.19 перестали работать спецэффекты в режиме dialog

### ISSUE THREAD

**Issue by vsmith80** [AlexxIT/YandexStation#677]
Перестали работать звуки из библиотеки звуков в режиме dialog

```
entity_id: media_player.yandex_station_main
data:
  media_content_id: >
    <speaker audio="alice-sounds-game-win-1.opus"> sil <[500]> {{
    "Здравствуйте! }} sil <[500]>
    <speaker audio="alice-sounds-game-win-2.opus">
  media_content_type: dialog
  extra:
    volume_level: 0.7
enabled: true
action: media_player.play_media
```

Вот это вместо звуков стало проигрываться так: "Знак меньше спикер одио равно элис саундс гейм вин минус один опус Здравствуйте спикер одио равно элис саундс гейм вин минус два опус знак больше"

Если поменять медиа контент тип на text - работает как и раньше - звучит звук из библиотеки звуков, потом проговаривается "Здравствуйте", потом второй звук.
