### ISSUE TITLE
не добавляется устройство Телевизор

### ISSUE THREAD

**Issue by AlexKash500** [AlexxIT/YandexStation#72]
При конфигурации 

```
yandex_station:
  username: XXXXX
  password: XXXXX
  recognition_lang: ru-RU
  include:
  - Кондиционер  # имя 
  - Телевизор 
```

![image](https://user-images.githubusercontent.com/69472472/97787612-5cd5fd80-1bc4-11eb-8a6a-af5374660b90.png)

Кондиционеры пробрасываются в HA, а ТВ нет. (устрйоства remote не появляются)
В чем может быть проблема?
