### ISSUE TITLE
Работают только media_content_type: text или command 

### ISSUE THREAD

**Issue by 2053950** [AlexxIT/YandexStation#78]
```
trigger:
    platform: event
    event_type: telegram_text
  action:
    service: media_player.play_media
    entity_id: media_player.yandex_station_900000000000  # замените на вашу станцию
    data_template:
      media_content_id: "{{ trigger.event.data.text }}"
      media_content_type: text  # или command
```

Работают только media_content_type: text или command 
text - воспроизводит text
command - выполняет команду.
Триггер, который должен отвечать в бот не вызывается при этом.
 ```
trigger:
    platform: event
    event_type: yandex_station_response
  action:
    service: telegram_bot.send_message
    data_template:
      target: "{{ trigger.event.data.request_id }}"
      message: "{{ trigger.event.data.text }}"


```
Указание media_content_type: question как в примере вызывает ошибку:
Unsupported media: question

При этом попытка передать ссылку на youtube  (что comma) вызывает ошибку 'Команда Алисе может содержать только кириллицу, латиницу, цифры и спецсимволы: "-,!.:=?"
